version: '3'

services:
  web1:
    image: containous/whoami
    labels:
      - traefik.http.routers.www1.rule=Host(`www1.maciek.local`)
      - traefik.http.services.www1.loadbalancer.server.port=80
    networks:
      traefik:

  web2:
    image: jwilder/whoami
    labels:
      - traefik.http.routers.www2.rule=Host(`www2.maciek.local`)
      - traefik.http.services.www2.loadbalancer.server.port=8000
    networks:
      traefik:
    
networks:
  traefik:
    external: true